export const company = {
  legalName: "Daxar Enterprises LLC",
  shortName: "Daxar Enterprises",
  email: "info@daxarenterprises.com",
  phonePrimary: "706-955-4742",
  phonePrimaryHref: "tel:+17069554742",
  phoneSecondary: "912-656-7940",
  phoneSecondaryHref: "tel:+19126567940",
  cage: "1AXU9",
  uei: "CHHQZLPNT1F7",
  samStatus: "Active",
  coverage: "Nationwide",
  naicsPrimary: {
    code: "236220",
    title: "Commercial and Institutional Building Construction",
  },
  naicsSecondary: [
    { code: "238110", title: "Poured Concrete Foundation and Structure Contractors" },
    { code: "238160", title: "Roofing Contractors" },
    { code: "238220", title: "Plumbing, Heating, and Air-Conditioning Contractors" },
    { code: "238310", title: "Drywall and Insulation Contractors" },
    { code: "238320", title: "Painting and Wall Covering Contractors" },
    { code: "238330", title: "Flooring Contractors" },
    { code: "238350", title: "Finish Carpentry Contractors" },
    { code: "238910", title: "Site Preparation Contractors" },
    { code: "238990", title: "All Other Specialty Trade Contractors" },
  ],
  siteUrl: "https://www.daxarenterprises.com",
} as const;
